name: github-pages
on:
  schedule:
    - cron: "04 16 * * *"
  # push:
  #   branches: ["main"]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          cache: yarn
          node-version: "16"

      # - name: Cache dependencies
      #   uses: actions/cache@v2
      #   with:
      #     path: |
      #       **/node_modules
      #     key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
      - name: Install Dependency
        run: yarn install
      - name: Build
        run: yarn vercel-build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
